[build]
  command = "npm install" 
  publish = "/" 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth/apple/callback"
  to = "/.netlify/functions/server/auth/apple/callback"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = false