[build]
  command = "npm install && npm run build --if-present"
  publish = "dist/appleAuthFromJs/browser/"

[build.environment]
  NODE_VERSION = "20" 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/server"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200