[build]
  command = "npm install && npm run build"
  publish = "dist/appleAuthFromJs/browser/"

[build.environment]
  NODE_VERSION = "20" 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirect all non-function requests to index.html for Angular SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  # Don't redirect function calls, API calls, or static assets
  force = false